name: Pipeline CI/CD #nome do workflow, que aparece na "Actions".

on: #Definir quando o pipeline será disparado.
  push:
    branches:
      - main
  workflow_dispatch: #habilitar o botão "Run workflow" no Github Actions.

jobs: #Definir um conjunto de passos para a etapa do pipeline que estamos criando.
 #Primeiro job: build
 build:
    runs-on: ubuntu-latest #Imagem da maquina usada no CI.
   
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Instalação das depêndencias
        run: npm install
        
      - name: Rodar o build
        run: npm run build
        env:
          NEXT_PUBLIC_TMDB_BASE_URL: ${{ vars.NEXT_PUBLIC_TMDB_BASE_URL }}
          NEXT_PUBLIC_TMDB_API_KEY: ${{ secrets.NEXT_PUBLIC_TMDB_API_KEY }}
          NEXT_PUBLIC_TMDB_API_IMG_URL: ${{ vars.NEXT_PUBLIC_TMDB_API_IMG_URL }}
